### ISSUE TITLE
Question about ContainersNotReady pod status

### ISSUE THREAD

**Issue by omerozery** [wongnai/kube-slack#28]
Why the blacklistReason array of PodStatus class constructor doesn't contain ContainersNotReady ?
I get a lot of messages of that kind every time i apply new deployment, even though eventually they are deployed successfully.
it is making my slack channel very noisy and unreliable.

**Comment by whs** [comment]
#27 just came in at the same time :D

Are you having the same issue that your application pod takes very long time to boot and get notified as well?

**Comment by whs** [comment]
Actually I think I know the problem. I'll take a look later this week. Merging with #27
