### ISSUE TITLE
Proxy setting to reach slack webhooks.

### ISSUE THREAD

**Issue by Saggi432** [wongnai/kube-slack#34]
Firstly, thank you so much for providing this capability.. i am sure this is going to help to monitor the k8s infra...below is my query to run inside a corporate network..

I am running inside a corporate network, so i tried setting the http_proxy, https_proxy as env variables. I also set the proxy https_proxy in the .npmrc..but still i face the below error from the pod logs

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 201)
(node:1) UnhandledPromiseRejectionWarning: Error: tunneling socket could not be established, cause=connect EINVAL 0.0.35.130:80 - Local (0.0.0.0:0)
    at 

My NPM config on the pod looks like below..

app $ npm config ls
; cli configs
metrics-registry = "https://ok-repo.ok.com/nodejs/content/groups/npm/"
scope = ""
user-agent = "npm/5.6.0 node/v8.11.2 linux x64"

; project config /app/.npmrc
https-proxy = "proxy-appgw.ok.com:9090"
registry = "https://ci-repo.ok.com/nodejs/content/groups/npm/"

; userconfig /home/kube-slack/.npmrc
http_proxy = "http://proxy-appgw.ok.com:9090"
https_proxy = "http://proxy-appgw.ok.com:9090"
proxy = "http://proxy-appgw.ok.com:9090/"

; node bin location = /usr/local/bin/node
; cwd = /app
; HOME = /home/kube-slack
; "npm config ls -l" to show all defaults.

**Comment by whs** [comment]
The npm settings are for npm commands only.

We're using Slack's SDK behind the scene, so [this is how the docs says how to do it](https://slackapi.github.io/node-slack-sdk/web_api#custom-agent-for-proxy-support) and added to [this file](https://github.com/wongnai/kube-slack/blob/07caafd67b38dbf8a6b96c2fb0cfe5801d83f3f6/src/notify/slack.js#L8).

**Comment by whs** [comment]
Oh wait, we're using node-slack

https://github.com/xoxco/node-slack/blob/81ed5dd5d91dd0d15b1adeb7d8cea270406752fe/slack.js#L31

so setting https_proxy or http_proxy should work...

I'm guessing that maybe Kubernetes API access is proxied too. Could you check your proxy server logs (or [tcpdump](https://serverfault.com/questions/362529/how-can-i-sniff-the-traffic-of-remote-machine-with-wireshark))?

**Comment by Saggi432** [comment]
Thank you for the reply.. 

you mean the logs on the proxy server..?

**Comment by whs** [comment]
Yup, I'd like to know how the proxy get used.

On reading the original logs again, I noticed it mentioned `EINVAL 0.0.35.130:80`. Is that IP your proxy server? And is the 0.0 prefix redacted or is it that way in the log.

**Comment by Saggi432** [comment]
The IP is not the proxy server IP.

I went to the pod shell and set the https_proxy manually and ran the following from the command line. this time its a different error..

app $ node .
{"name":"kube-slack","hostname":"kube-slack-5df468977d-845w9","pid":47,"level":30,"msg":"Kubernetes monitors started","time":"2018-05-23T23:38:22.582Z","v":0}

node:47) UnhandledPromiseRejectionWarning: Error: tunneling socket could not be established, statusCode=403
    at ClientRequest.onConnect (/app/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
    at ClientRequest.emit (events.js:217:7)
    at Socket.socketOnData (_http_client.js:474:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
(node:47) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:47) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Saggi432** [comment]
Hi..
i did a try by enabling the http_noproxy as well to make sure the k8s cluster does not use proxy when it makes its call.. but still the 403 error comes up.. i will dig further and update you.

**Comment by whs** [comment]
I just added SLACK_PROXY option in master. Could you please try the image with latest tag?

**Comment by Saggi432** [comment]
sure..
let me give a try..thank you!

**Comment by Saggi432** [comment]
Hi,
I just tried with the new changes in master..it looks to have an error..there is a conflict with config directory..cannot find the module config.

internal/modules/cjs/loader.js:596
    throw err;
    ^
Error: Cannot find module 'config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.&lt;anonymous&gt; (/app/src/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)

**Comment by whs** [comment]
You can use the prebuilt image on Docker hub (tagged latest).

For that error I believe you haven't run npm install or config module is
missing from packages.json.
