### ISSUE TITLE
Feature Request - Option of Slack Username

### ISSUE THREAD

**Issue by vikas027** [wongnai/kube-slack#39]
It would be good to have an option to define `SLACK_USERNAME` in order override the default username `incoming-webhook`

**Comment by whs** [comment]
You can configure the username from Slack's incoming webhook configuration. Is there any use case missing from this?

If you're on the free tier, each instances of incoming webhook are not counted as separate integrations.

**Comment by whs** [comment]
You can create 3 incoming webhooks that point to the same channels with different name. That's what we're using as well.

**Comment by vikas027** [comment]
Yes, but IMHO that is a work around and then has limits. It would still be convenient to have variable `SLACK_USERNAME` so that we don't need to have multiple hooks, and just one hook is sufficient for all alerts. I have plans to have more services alerting to the same channel.

**Comment by whs** [comment]
I'm sorry but adding this feature which has equivalent option available would cause additional maintenance work on our part.

**Comment by vikas027** [comment]
It is up to you, equivalent options are **not** really equivalent when you have multiple applications pointing to the same channel.
