### ISSUE TITLE
kube-slack can mix-up different pods if they have same label

### ISSUE THREAD

**Issue by max-lobur** [wongnai/kube-slack#45]
In my case both have label `app: grafana`.
The 1st is in crash loop, the 2nd one is running more than a month without any move. It clearly mixed up these two when reported `Container entered status *Running*`

![image](https://user-images.githubusercontent.com/5246026/49244776-42fc7080-f419-11e8-9642-09c2a05ae2d3.png)

k8s 1.10
kube-slack v3.6.0

**Comment by blandman** [comment]
Created MR that should resolve this, issue was the running notification was matching just the pod name, which is the same in this scenario. New MR matches on namespace/pod name.

**Comment by whs** [comment]
Released as v3.7.1 on Docker Hub
