### ISSUE TITLE
Lots of errors when upgrading to 4.0.1

### ISSUE THREAD

**Issue by roffe** [wongnai/kube-slack#50]
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
(node:1) UnhandledPromiseRejectionWarning: Error: Failed to get /openapi/v2 and /swagger.json: Unauthorized
    at _getSpec.catch.then.catch.err (/app/node_modules/kubernetes-client/lib/swagger-client.js:56:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
(node:1) UnhandledPromiseRejectionWarning: Error: Failed to get /openapi/v2 and /swagger.json: Unauthorized
    at _getSpec.catch.then.catch.err (/app/node_modules/kubernetes-client/lib/swagger-client.js:56:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
(node:1) UnhandledPromiseRejectionWarning: Error: Failed to get /openapi/v2 and /swagger.json: Unauthorized
    at _getSpec.catch.then.catch.err (/app/node_modules/kubernetes-client/lib/swagger-client.js:56:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
(node:1) UnhandledPromiseRejectionWarning: Error: Failed to get /openapi/v2 and /swagger.json: Unauthorized
    at _getSpec.catch.then.catch.err (/app/node_modules/kubernetes-client/lib/swagger-client.js:56:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)

**Comment by whs** [comment]
The Kubernetes client we use has a flag that prevent credentials from being sent to API server. (I don't know why they have that set)

I've submitted a PR to upstream. In the mean time v3.7.1 should not be affected as we recently bumped API client version.

**Comment by whs** [comment]
I've been busy. Sorry for the wait.

This issue has been fixed in master. I'm running the :latest from Docker Hub to validate for a few more days before releasing.

In long term, I think moving to https://github.com/kubernetes-client/javascript will get us better type definition and also official support.

**Comment by whs** [comment]
Released as v4.1.1
